### ISSUE TITLE
Move the NGINX conf template to ConfigMap object

### ISSUE THREAD

**Issue by nettoclaudio** [tsuru/rpaas-operator#18]
Today we've the `nginx.conf`'s template inside the rpaas-controller source code. It means any needed change into `nginx.conf` template requires changing the source code and redeploy the controller in the cluster. That's awful.

I suggest moving this main template to a ConfigMap and associate that with a new field into RpaasPlan, e.g.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-template
  namespace: default
data:
  nginx.conf.tmpl: -|
    user {{with .Config.User}}{{.}}{{else}}nginx{{end}};
    worker_processes {{with .Config.WorkerProcesses}}{{.}}{{else}}1{{end}};
    include modules/*.conf;
    events {
        worker_connections {{with .Config.WorkerConnections}}{{.}}{{else}}1024{{end}};
    }
    # ...
---
apiVersion: extensions.tsuru.io/v1alpha1
kind: RpaasPlan
metadata:
  name: my-plan
spec:
  image: tsuru/nginx-tsuru:1.16.0
  nginxTemplate:
    configMapName: nginx-conf-template
    namespace: default
    key: nginx.conf.tmpl
---
apiVersion: extensions.tsuru.io/v1alpha1
kind: RpaasInstance
metadata:
  name: my-instance
spec:
  planName: my-plan
```
